import Header from "@/components/global/header/header";
import "./globals.css";
import Footer from "@/components/global/footer/footer";

export const metadata = {
  title: "Vlad",
  description: "Generated by Vlad",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <script src="https://apis.google.com/js/api.js"></script>
      </head>
      <body>
        <Header />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
